<template>
  <div class="section-block">
    <pre><code class="language-markup">  &#x3C;div class=&#x22;bd-example&#x22;&#x3E;
    &#x3C;nav class=&#x22;nav&#x22;&#x3E;
      &#x3C;a class=&#x22;nav-link active&#x22; aria-current=&#x22;page&#x22; href=&#x22;#&#x22;&#x3E;Active&#x3C;/a&#x3E;
      &#x3C;a class=&#x22;nav-link&#x22; href=&#x22;#&#x22;&#x3E;Link&#x3C;/a&#x3E;
      &#x3C;a class=&#x22;nav-link&#x22; href=&#x22;#&#x22;&#x3E;Link&#x3C;/a&#x3E;
      &#x3C;a class=&#x22;nav-link disabled&#x22; href=&#x22;#&#x22; tabindex=&#x22;-1&#x22;&#x3E;Disabled&#x3C;/a&#x3E;
    &#x3C;/nav&#x3E;
  &#x3C;/div&#x3E;
  &#x3C;div class=&#x22;bd-example&#x22;&#x3E;
    &#x3C;nav&#x3E;
      &#x3C;div class=&#x22;mb-3 nav nav-tabs&#x22; id=&#x22;nav-tab&#x22; role=&#x22;tablist&#x22;&#x3E;
        &#x3C;button class=&#x22;nav-link active d-flex align-items-center&#x22; id=&#x22;nav-home-tab&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#nav-home&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-controls=&#x22;nav-home&#x22; aria-selected=&#x22;true&#x22;&#x3E;Home&#x3C;/button&#x3E;
        &#x3C;button class=&#x22;nav-link&#x22; id=&#x22;nav-profile-tab&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#nav-profile&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-controls=&#x22;nav-profile&#x22; aria-selected=&#x22;false&#x22;&#x3E;Profile&#x3C;/button&#x3E;
        &#x3C;button class=&#x22;nav-link&#x22; id=&#x22;nav-contact-tab&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#nav-contact&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-controls=&#x22;nav-contact&#x22; aria-selected=&#x22;false&#x22;&#x3E;Contact&#x3C;/button&#x3E;
      &#x3C;/div&#x3E;
    &#x3C;/nav&#x3E;
    &#x3C;div class=&#x22;tab-content iq-tab-fade-up&#x22; id=&#x22;simple-tab-content&#x22;&#x3E;
      &#x3C;div class=&#x22;tab-pane fade show active&#x22; id=&#x22;nav-home&#x22; role=&#x22;tabpanel&#x22; aria-labelledby=&#x22;nav-home-tab&#x22;&#x3E;
        &#x3C;p&#x3E;&#x3C;strong&#x3E;This is some placeholder content the Home tab&#x27;s associated content.&#x3C;/strong&#x3E; Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling. You can use it with tabs, pills, and any other &#x3C;code&#x3E;.nav&#x3C;/code&#x3E;-powered navigation.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
      &#x3C;div class=&#x22;tab-pane fade&#x22; id=&#x22;nav-profile&#x22; role=&#x22;tabpanel&#x22; aria-labelledby=&#x22;nav-profile-tab&#x22;&#x3E;
        &#x3C;p&#x3E;&#x3C;strong&#x3E;This is some placeholder content the Profile tab&#x27;s associated content.&#x3C;/strong&#x3E; Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling. You can use it with tabs, pills, and any other &#x3C;code&#x3E;.nav&#x3C;/code&#x3E;-powered navigation.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
      &#x3C;div class=&#x22;tab-pane fade&#x22; id=&#x22;nav-contact&#x22; role=&#x22;tabpanel&#x22; aria-labelledby=&#x22;nav-contact-tab&#x22;&#x3E;
        &#x3C;p&#x3E;&#x3C;strong&#x3E;This is some placeholder content the Contact tab&#x27;s associated content.&#x3C;/strong&#x3E; Clicking another tab will toggle the visibility of this one for the next. The tab JavaScript swaps classes to control the content visibility and styling. You can use it with tabs, pills, and any other &#x3C;code&#x3E;.nav&#x3C;/code&#x3E;-powered navigation.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
    &#x3C;/div&#x3E;
  &#x3C;/div&#x3E;
  &#x3C;div class=&#x22;bd-example&#x22;&#x3E;
    &#x3C;ul class=&#x22;nav nav-pills&#x22; data-toggle=&#x22;slider-tab&#x22; role=&#x22;tablist&#x22;&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22; role=&#x22;presentation&#x22;&#x3E;
        &#x3C;button class=&#x22;nav-link active d-flex align-items-center&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#pills-home1&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-selected=&#x22;true&#x22;&#x3E;Home&#x3C;/button&#x3E;
      &#x3C;/li&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22; role=&#x22;presentation&#x22;&#x3E;
        &#x3C;button class=&#x22;nav-link d-flex align-items-center&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#pills-profile1&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-selected=&#x22;false&#x22;&#x3E;Profile&#x3C;/button&#x3E;
      &#x3C;/li&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22; role=&#x22;presentation&#x22;&#x3E;
        &#x3C;button class=&#x22;nav-link&#x22; id=&#x22;contact-tab&#x22; data-bs-toggle=&#x22;tab&#x22; data-bs-target=&#x22;#pills-contact1&#x22; type=&#x22;button&#x22; role=&#x22;tab&#x22; aria-selected=&#x22;false&#x22;&#x3E;Contact&#x3C;/button&#x3E;
      &#x3C;/li&#x3E;
    &#x3C;/ul&#x3E;
    &#x3C;div class=&#x22;tab-content iq-tab-fade-up&#x22;&#x3E;
      &#x3C;div class=&#x22;tab-pane fade show active&#x22; id=&#x22;pills-home1&#x22; role=&#x22;tabpanel&#x22;&#x3E;
        &#x3C;p&#x3E;Raw denim you probably haven&#x27;t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.&#x3C;/p&#x3E;
        &#x3C;p&#x3E;Raw denim you probably haven&#x27;t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
      &#x3C;div class=&#x22;tab-pane fade&#x22; id=&#x22;pills-profile1&#x22; role=&#x22;tabpanel&#x22;&#x3E;
        &#x3C;p&#x3E;Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
      &#x3C;div class=&#x22;tab-pane fade&#x22; id=&#x22;pills-contact1&#x22; role=&#x22;tabpanel&#x22;&#x3E;
        &#x3C;p&#x3E;Raw denim you probably haven&#x27;t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.&#x3C;/p&#x3E;
        &#x3C;p&#x3E;Raw denim you probably haven&#x27;t heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse.&#x3C;/p&#x3E;
      &#x3C;/div&#x3E;
    &#x3C;/div&#x3E;
  &#x3C;/div&#x3E;
  &#x3C;div class=&#x22;bd-example mb-5&#x22;&#x3E;
    &#x3C;ul class=&#x22;nav nav-pills&#x22;&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22;&#x3E;
        &#x3C;a class=&#x22;nav-link active&#x22; aria-current=&#x22;page&#x22; href=&#x22;#&#x22;&#x3E;Active&#x3C;/a&#x3E;
      &#x3C;/li&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22;&#x3E;
        &#x3C;a class=&#x22;nav-link&#x22; href=&#x22;#&#x22;&#x3E;Link&#x3C;/a&#x3E;
      &#x3C;/li&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22;&#x3E;
        &#x3C;a class=&#x22;nav-link&#x22; href=&#x22;#&#x22;&#x3E;Link&#x3C;/a&#x3E;
      &#x3C;/li&#x3E;
      &#x3C;li class=&#x22;nav-item&#x22;&#x3E;
        &#x3C;a class=&#x22;nav-link disabled&#x22; href=&#x22;#&#x22; tabindex=&#x22;-1&#x22;&#x3E;Disabled&#x3C;/a&#x3E;
      &#x3C;/li&#x3E;
    &#x3C;/ul&#x3E;
  &#x3C;/div&#x3E;
        </code></pre>
  </div>
</template>
